// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace InventoryNoAuth.Models
{
    public partial class MCellList
    {
        public string Cell { get; set; }
        public string CellName { get; set; }
        public int? PartCnt { get; set; }
    }
}