// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace InventoryNoAuth.Models
{
    public partial class MCpositioncodePart
    {
        
        public string Id { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Part { get; set; }
        public string Rank { get; set; }
        public string RankFinal { get; set; }
        public decimal Iqty { get; set; }
    }
}