// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace InventoryNoAuth.Models
{
    public partial class MCpositioncode
    {
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public int? Cnt { get; set; }
    }
}