// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace InventoryNoAuth.Models
{
    public partial class MFullpartList
    {
        public string Fullpart { get; set; }
        public string Part { get; set; }
        public string Rank { get; set; }
        public string RankFinal { get; set; }
        public int? CellCnt { get; set; }
    }
}