// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace InventoryNoAuth.Models
{
    public partial class MPartList
    {
        public string Part { get; set; }
        public int? RankCnt { get; set; }
        public int? CellCnt { get; set; }
    }
}