// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace InventoryNoAuth.Models
{
    public partial class StockCurrentAdjustD
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Cpositioncode { get; set; }
        public string Cpositionname { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Sncode { get; set; }
        public decimal Oriqty { get; set; }
        public decimal Newqty { get; set; }
        public string Createowner { get; set; }
        public DateTime Createtime { get; set; }
        public string Lastupdateuser { get; set; }
        public DateTime? Lastupdatetime { get; set; }

        public virtual StockCurrentAdjust IdNavigation { get; set; }
    }
}