// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace InventoryNoAuth.Models
{
    public partial class StockCurrent
    {
        public string Id { get; set; }
        public string Cstatus { get; set; }
        public string Cwarehouse { get; set; }
        public string Cwarehousecode { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal Iqty { get; set; }
        public string Cunits { get; set; }
        public string Cdatecode { get; set; }
        public string Cbarcode { get; set; }
        public decimal Ioccupyqty { get; set; }
        public string Cmemo { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public DateTime? Ddefine3 { get; set; }
        public DateTime? Ddefine4 { get; set; }
        public decimal? Idefine5 { get; set; }
        public decimal Iplanin { get; set; }
        public decimal Iplanout { get; set; }
        public string Palletcode { get; set; }
    }
}