// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace InventoryNoAuth.Models
{
    public partial class StockCurrentAdjust
    {
        public StockCurrentAdjust()
        {
            StockCurrentAdjustD = new HashSet<StockCurrentAdjustD>();
        }

        public string Id { get; set; }
        public string Cticketcode { get; set; }
        public string Reason { get; set; }
        public string Cstatus { get; set; }
        public string Createowner { get; set; }
        public DateTime Createtime { get; set; }
        public string Reviewuser { get; set; }
        public DateTime? Reviewtime { get; set; }
        public string Lastupdateuser { get; set; }
        public DateTime? Lastupdatetime { get; set; }

        public virtual ICollection<StockCurrentAdjustD> StockCurrentAdjustD { get; set; }
    }
}