// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace InventoryNoAuth.Models
{
    public partial class StockCurrentSn
    {
        public string Ids { get; set; }
        public string StockId { get; set; }
        public string Sncode { get; set; }
        public decimal? Datecode { get; set; }
        public decimal? Qty { get; set; }
        public string Cstatus { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createuser { get; set; }
        public DateTime? Lastupdatetime { get; set; }
        public string Lastupdateuser { get; set; }
        public decimal? Sntype { get; set; }
        public string Furnaceno { get; set; }
        public string Memo { get; set; }
        public string Default2 { get; set; }
        public string Stocktype { get; set; }
        public string SnCode20 { get; set; }
        public string Palletcode { get; set; }
        public string Erpcode { get; set; }
        public string Vendorcode { get; set; }
        public string Rulecode { get; set; }
    }
}